sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: fmHZi9u7TkE/1hVqnI5h5498k8PfEW8YRSYPmthNf6rYPOUiWQroBYZrw6Po7PZZRTpY/aS6dcqjvxmgG0Js3Nd7pYXFk2gIu+UBaABQ5Csq/dHRYPjOxCuITs/HONdaxP0mPNZ2rco/VUieqBWoIWH6y/QOJwIEsw07xw5KS+5bvQnlG21IvjuX/EZnvkHBT6L7RA/ohK/mXOMHjrrlcz/w6fkbcCdGBjoWj7OuM3U4SIVIpQjxf1ua8KpkiQwna9UajDbTmXncI8zzEp2XLMsqcFaCL/ry5JdEVnEvo1SOzXR/xFHNy7VnPz6+LwZ/nFfJkEOc63xnGh4fAHSRMZNmdRtQo4aqigHUI0hGc+tsTJQZ0GAVDaNPYVSnLc/34HNUTg4Y7CuDlK0HwLit8EXBTtoMB988aS+PyNGR7dbfIBZptdoB9B4hE5bOc4HcZ24+Pj9hWmAVAYCNuPQzBIrYC2hq++Wr/QvhU+5YL1mFxFMXAlvojWx1JuWWqz2UtAw7hD5i01OrUv8InliE9IYaQTn/l9mkwqG+VApHdQP3N8qW0bo7IdAqTRFRf/YkkIZ/gEG88FfpxCjXoZ2YQXoermSwmYXWLsYErTfmZZn7iB3AiE/ErT4aabdRRG/qZZI4IRDbyy17pzMJm4p4B2EhsXSfjmtr484GcA30eT0=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: p6aAbrmeF69rykWBPQUdjxTxT0QVQPlmo7zHwFWzM8OPKCAv9h9o8uXAeEAeQAM1uZSWPxYGP5IyET6whdxM4hHljzQGnxjkBJC0WUhP7r/nFCX3wVUGu9DXajTKLwe+dCdNPqYgi91eZfecPKyT4/8X3LbUuTe0tZq/m40/Vy5AF4F6XC4XZHfMgqnYge75L88oIxrJSvRaar1HKOh9R4/JVmaLuE0mF+KcwM7SUNWSwYFVybrNkkbbPBSKPdlCG6QaCgeLMKSVb+6DEUN7mNduihU2KFPBdpVn4p3EScF8yb+bam8S0qg2cEXubZAVRoq5x+ww5+cTbExkks4GFgu7xnLVDjtkSVq96YsSqBqT/0nJe+GPUX3Trt+ivS0Dt1G0Ld05KxpOgocXwn5kXFO5U4Ly0K718C3tBBPNAsw73cDZ+j1mexgW1a/NYZbqFUTEcf2ILveoxbGO3S4P6AVjtxS/drJNNbYmYCP0HeCyGn5WcIvbMheZmzU83176G+jkyz4TFDQUQYTxI++7aU4nXKPmS4WXoMwEcYLFobNn5uB88nsgcmuIfoZO5qh6maHkmDgs8S7LjQnH37gbNKMX/98icrupVoVinV8ecSOO1X9Vp9NpYrV+zqUlqkj+63EGa8a3XWxOSZjCzxV4cNV67twjDQwjOec1n52uvfo=
